### ISSUE TITLE
Implement Authorization

### ISSUE THREAD

**Issue by spacejam** [tower-rs/tower-grpc#101]
Is there a tracking issue or anything for the auth implementation? I am trying to scope the work required to talk to GCE using tower-grpc, and am curious what the current state of this is. Thanks for your time :]

**Comment by seanmonstar** [comment]
Features are added as they are needed by contributors :D. We haven't needed it yet, but we can mentor your contributions if you'd like to be that person!

**Comment by spacejam** [comment]
The reason I ask is because I see things like #26 and the crossed-out items on the tower-grpc-interop README.md. I'd like to avoid any duplication of effort, and I'd like to read anything that has been written up about required pieces. It seems like at some point someone specced out to some degree how to talk to google cloud services using service accounts, and if that resulted in any notes or anything it would be valuable to check against what I've gathered so far.

**Comment by nevi-me** [comment]
Hi @spacejam, how does Google auth work on gRPC? I've only ever used custom auth by sending JWTs as part of the metadata. To achieve that, I create an interceptor that manages auth (refresh tokens in the background, respond to auth-related errors).
Though that's in different languages, the concept could be ported to Rust if I spend enough time getting to understand how tower works (I've only used basic functionality so far).

**Comment by spacejam** [comment]
docs.rs/yup-oauth2 has support for using service accounts with Hyper. @seanmonstar do you see this approach as being very reusable for getting service accounts working with tower-grpc?

**Comment by seanmonstar** [comment]
@spacejam The surface area when I look at the docs seems large, so I don't know what exactly to look for. Would you be able to come up with a report answering your own question? :D

**Comment by spacejam** [comment]
@seanmonstar I think this boils down to attaching a bearer token on an http2 request sent over TLS. Are there any examples for attaching a bearer token for a gRPC request?

**Comment by spacejam** [comment]
yup_oauth2 wraps hyper requests with this token

**Comment by seanmonstar** [comment]
Without any additional library, you can attach "metadata" to a `Request` via `metadata_mut()`. You could add a bearer token like that.

**Comment by nevi-me** [comment]
gRPC implementations that support interceptors do that automatically to the metadata. One would have to do that manually in tower-grpc's case. @spacejam if you go that route, make consideration for retries on auth errors if your tokens can expire, so you can refresh/update token and retry a request.

**Comment by spacejam** [comment]
experiencing quite a bit of friction getting a round trip going to google APIs, is there an obvious issue that jumps out to you folks, @seanmonstar, @carllerche ? it's blowing up on line 161 with broken pipe. logs included below 

code:
https://gist.github.com/rust-play/f0fc6a4f985aea96fabf6890afbbf2af

logs:
[out.sanitized.log](https://github.com/tower-rs/tower-grpc/files/3034365/out.sanitized.log)

**Comment by LucioFranco** [comment]
@spacejam not totally sure, but h2 requires that you have negotiated for http2 via alpn or upgrade header and I dont see that happening https://gist.github.com/rust-play/f0fc6a4f985aea96fabf6890afbbf2af#file-playground-rs-L227 that might be the issue, I remember having similar issues.

**Comment by carllerche** [comment]
This h2 example shows a bit how to do ALPN negotiation: https://github.com/carllerche/h2/blob/master/examples/akamai.rs

Unfortunately, things are very manual right now.

**Comment by carllerche** [comment]
I'm going to close this as I believe the issue turned out to be ALPN negotiation. Feel free to continue discussion here though.

**Comment by spacejam** [comment]
it's not yet clear that this was the issue

**Comment by qm3ster** [comment]
So what actually *is* gRPC auth after all? Is it really just a `Authorization: Bearer`*`SIGNED_JWT`* header on the request?

**Comment by nevi-me** [comment]
> So what actually _is_ gRPC auth after all? Is it really just a `Authorization: Bearer`_`SIGNED_JWT`_ header on the request?

It depends, in most cases it is passing a `Bearer` token, but that's what happens in the transport. Given that OAuth tokens expire, sometimes an auth implementation becomes responsible for making sure that tokens are (still) valid before sending them.
