### ISSUE TITLE
RPC from tower-grpc client to grpc-go server fails with broken pipe

### ISSUE THREAD

**Issue by hawkw** [tower-rs/tower-grpc#12]
When a `tower-grpc` client calls a service on a server using the `grpc-go` gRPC implementation, the RPC fails with a broken pipe error:
```
Inner(Error { kind: Inner(Error { kind: Io(Error { repr: Kind(BrokenPipe) }) }) })
```

### Background

I first encountered this issue working on #3 (implementing the gRPC interop tests). I was working on writing the client for the interop tests, and as I had not yet written a server implementing the test RPCs, I was testing my client against the `grpc-go` interop test server, which seemed like a canonical reference implementation. Attempting to call any of the RPCs in the interop test proto resulted in this error. 

I initially suspected a bug in my code, but after trying an [extremely stripped-down client](https://github.com/tower-rs/tower-grpc/blob/cd0d7ed3ceb607d3c445b85a5ef535c9e9cc6995/tower-grpc-examples/src/interop/empty_unary_client.rs) copied from the hello world client in `tower-grpc-examples` that only calls the simplest RPC on the test service, an empty unary call, I wondered if it was really my fault. I then tested the hello world client from the latest `tower-grpc` master against the hello world server in `grpc-go`. Since these example programs are extremely simple and don't rely on any features that `tower-grpc` doesn't currently implement, I'd expect them to be interoperable. However, trying the `tower-grpc` `helloworld-client` against `grpc-go`'s `greeter_server` fails with the same broken pipe error. When the `tower-grpc` client calls `tower-grpc`'s `helloworld-server`, or a Go client calls the Go server, everything works fine.

### What seems to be going wrong

I tried using `tshark` to sniff the connection between the client and server, and it appears that what's happening is that after the server receives the request, it responds with a TCP `ACK` packet followed by a `FIN, ACK` packet. The client complies with the `FIN, ACK` and closes the connection. I have no idea _why_ `grpc-go` is flat-out refusing to talk to us, though.

Here's [the complete output of the `tshark` capture](https://gist.github.com/hawkw/1c5818f17962c4aa2e531ef5f2896f84#file-tshark-capture), and here's the [logs output from the client with `RUST_LOG=trace`](https://gist.github.com/hawkw/1c5818f17962c4aa2e531ef5f2896f84#file-helloworld-log). 

I'd like to get logs out of the Go server as well, but I haven't been able to figure out _how_ yet; it doesn't seem to be documented anywhere as far as I can tell. Maybe a Go person could give some pointers in the right direction.

### Steps to reproduce
(assuming a working Rust and Go installation)
1. check out the latest master of `tower-grpc`.
2. get `grpc-go`, including dependencies for examples, with:
```
$ go get -u google.golang.org/grpc/...
```
3. start the hello world example server from `grpc-go`:
```
$ cd $GOPATH/src/google.golang.org/grpc/examples/helloworld
$ go run greeter_server/main.go
```
4. from the `tower-grpc` repo, run the hello world client:
```
$ cargo run -p tower-grpc-examples --bin helloworld-client
```
And that's it – the client should fail with a `BrokenPipe` error.

**Comment by hawkw** [comment]
Interestingly, testing with `grpc-java`'s helloworld example yields a different error:
```
$ cargo run -p tower-grpc-examples --bin helloworld-client  
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/helloworld-client`
thread 'main' panicked at 'gRPC request failed; err=Grpc(Status { code: Unimplemented })', tower-grpc-examples/src/helloworld/client.rs:47:28
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
and the server's logs say 
```
$ ./build/install/examples/bin/hello-world-server
Dec 28, 2017 2:31:12 PM io.grpc.examples.helloworld.HelloWorldServer start
INFO: Server started, listening on 50051
Dec 28, 2017 2:31:24 PM io.grpc.netty.NettyServerHandler onHeadersRead
WARNING: Expected header TE: trailers, but null is received. This means some intermediate proxy may not support trailers
```

This is curious, because [a `tshark` capture](https://gist.github.com/hawkw/1c5818f17962c4aa2e531ef5f2896f84#file-tshark-capture-grpc-java) seems to indicate that we _did_ send the `te: trailers` header.

**Comment by seanmonstar** [comment]
Yep, the rust logs also show sending trailers. Seems like the refactor made it so the client request streams might be sharing that code with the server, and sending trailers at the end.
