### ISSUE TITLE
Body trait should be removed in favor of tower-http

### ISSUE THREAD

**Issue by carllerche** [tower-rs/tower-grpc#125]
tower-grpc currently includes a [`Body` trait](https://github.com/tower-rs/tower-grpc/blob/98cc766e32d956e33b4b67ebe13f2634a79469bf/src/body.rs#L8-L28) that is a copy of the one that existed in `tower-h2`. This trait now lives in [`tower-http`](https://github.com/tower-rs/tower-http/blob/64585dd57e78a737dea29f952736ef2046f84238/tower-http-service/src/body.rs#L6-L20). 

Depends on https://github.com/tower-rs/tower-http/pull/10.

**Comment by seanmonstar** [comment]
Done.
