### ISSUE TITLE
Status should encode its message and details fields

### ISSUE THREAD

**Issue by seanmonstar** [tower-rs/tower-grpc#126]
A `Status` is correctly [decoded from metadata](https://github.com/tower-rs/tower-grpc/blob/98cc766e32d956e33b4b67ebe13f2634a79469bf/src/status.rs#L65), but is not [encoded](https://github.com/tower-rs/tower-grpc/blob/98cc766e32d956e33b4b67ebe13f2634a79469bf/src/status.rs#L122) before being inserted *into* metadata.

This causes `Status::to_header_map` to be fallible, which it shouldn't be.

**Comment by Emanon42** [comment]
Hi, I am currently preparing tokio GSOC project and reading source code of tower-grpc. I want to improve my understanding on project by fixing some easy issues. 
The links seem to point to old commits - now a new crate available function `add_header` does most job of original `to_header_map`. I guess you want to prevent calling `to_header_map` before the value of `Status` be decoded, is it?
I am still new to tower-grpc. Would you like to give me related mentions about how to fix this?

**Comment by seanmonstar** [comment]
The new commit doesn't really change the behavior, it just made it so a `Status` could be added to an existing `HeaderMap` instead of having to create a new one. It still doesn't encoded the status message.

Returning a custom status, like `Status::new(InvalidArgument, "look, an illegal\nchar")`, won't encode the message correctly, and so `add_header` will error.

If we implemented the server interop [special_status_message](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#special_status_message), it would show this bug.

**Comment by Emanon42** [comment]
Got it. I use `percent_encoding::utf8_percent_encode` to convert the illegal char to `%xx` and encode them to header. See https://github.com/tower-rs/tower-grpc/pull/135
