### ISSUE TITLE
Roadmap status update

### ISSUE THREAD

**Issue by oysterpack** [tower-rs/tower-grpc#142]
> I hope to get this to crates.io soon(ish) but there will be significant API changes before then. Hopefully that will happen by the end of 2018.

_Originally posted by @carllerche in https://github.com/tower-rs/tower-grpc/issues/87#issuecomment-429093518_

Any updates on this ?

**Comment by seanmonstar** [comment]
In the past several weeks, there's been a lot of activity here (on tower-grpc) and on its dependencies (tower). This repo has become a lot more robust, and more stable. That's as much as I know for a status update...

**Comment by carllerche** [comment]
Yeah... been trying to get the tower crates out first. Almost there, but I obviously and not very good at estimating. 

Do you have a dependency on grpc?

**Comment by hlb8122** [comment]
I've played around with a few grpc libraries now and this one feels so close and cuddly with futures + tokio. Love it and cannot wait for to get this to leave my local folders and live on crates.io! Keep up the great work guys.

**Comment by oysterpack** [comment]
Thanks for the updates. I have a strong dependency on grpc as a core API protocol. grpc has very strong momentum. It would be strategic for tower and for rust  to provide a robust, high-performing grpc solution. I believe it would help accelerate rust adoption on the server side and especially in the new micro-service architecture paradigm.

... even the PingCap team ([grpc-rs](https://crates.io/crates/grpcio) authors) is planning to migrate over to tower-grpc: [Use tower gRPC for TiKV](https://medium.com/@siddontang/use-tower-grpc-for-tikv-6109cf8c61)
