### ISSUE TITLE
High latency on simple grpc unary call

### ISSUE THREAD

**Issue by agend** [tower-rs/tower-grpc#149]
Hi,
  Implemented simple benchmark https://github.com/agend/tower-grpc-bench and got stable latency 40 ms per request (no concurrent access) . Is this expected behavior or it's tunable?

Thanks

**Comment by carllerche** [comment]
Did you factor in nagle? (tcp nodelay)?

**Comment by agend** [comment]
On server side - yes.

**Comment by carllerche** [comment]
The other usual culprit is not configuring the window size.

**Comment by olix0r** [comment]
The fact that the latency is 40ms, specificially, _strongly_ suggest that one side of the connection is not setting NODELAY... I suspect it must also be set on the client stream created here https://github.com/agend/tower-grpc-bench/blob/master/src/helloworld/client.rs#L77

**Comment by agend** [comment]
@olix0r Do you have an idea how to write this fix?

**Comment by agend** [comment]
Fixed it https://github.com/agend/tower-grpc-bench/blob/master/src/helloworld/client.rs#L78 . Now 1 ms and 1000 rps - as expected. Thx.
