### ISSUE TITLE
Path to publishing crate

### ISSUE THREAD

**Issue by rtyler** [tower-rs/tower-grpc#160]
It appears the crate [has not yet been published to crates.io](https://crates.io/crates/tower-grpc) and I was wondering if there were any outstanding tasks or areas where a contributor could help push tower-grpc over the finish line?

I would love to be able to depend on tower-grpc from some other crates :smile_cat:

**Comment by t-eckert** [comment]
I was thinking the same thing as @rtyler.

**Comment by carllerche** [comment]
First step is publishing `tower` crates, and that should happen within the next few days.

**Comment by brndnmtthws** [comment]
> First step is publishing `tower` crates, and that should happen within the next few days.

Legit. Say hi for me to the folks from Mesosphere 😀

**Comment by carllerche** [comment]
Tower crates are out. I think next is http-body.

**Comment by peterhuene** [comment]
With https://github.com/hyperium/http-body/issues/2 now closed, is the path to publishing http-body clear of issues?

**Comment by LucioFranco** [comment]
I believe the next steps are to publish `tower-hyper` and that will require us to finialize `HttpConnection` trait, that is sitting in a PR. But I have been on vacation so progress has been slow.

**Comment by peterhuene** [comment]
@LucioFranco thanks for the update.  We're really looking forward to a published tower-grpc 😄

**Comment by repi** [comment]
Also really looking forward here at Embark to having it published! We use it for a bunch of our gRPC services which has been working really well. But have been a little bit messy with so many in-development tower git repos as dependencies, but is understandable has worked.

**Comment by peterhuene** [comment]
@carllerche as you've now published a `0.1.0` of tower-grpc, should this issue now be closed?  Thanks!

**Comment by rtyler** [comment]
Closing myself
