### ISSUE TITLE
Content-Type not being set on server responses

### ISSUE THREAD

**Issue by brndnmtthws** [tower-rs/tower-grpc#166]
I've been trying to use [`grpc-health-probe`](https://github.com/grpc-ecosystem/grpc-health-probe) as a health check (`livenessProbe`) on my gRPC pods. Everything is great, except for one thing: tower-grpc is not setting the Content-Type header on server responses, thus grpc-health-probe fails like so:

```
grpc-health-probe -v -addr localhost:10011 -service MyService -tls -tls-ca-cert test/ca.crt -tls-client-cert test/client.crt -tls-client-key test/client.key
parsed options:
> addr=localhost:10011 conn_timeout=1s rpc_timeout=1s
> tls=true
  > no-verify=false
  > ca-cert=test/ca.crt
  > client-cert=test/client.crt
  > client-key=test/client.key
  > server-name=
establishing connection
connection establisted (took 14.765746ms)
error: health rpc failed: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field
```

Seems like the change in #70 got rolled back by accident? Was that intentional? Maybe there should be some integration tests to catch these interop things.

**Comment by brndnmtthws** [comment]
By the way, here's the relevant snippets of code:

```proto
syntax = "proto3";

package myservice;

service MyService {
  rpc Check(HealthCheckRequest) returns (HealthCheckResponse);
}

message HealthCheckRequest { string service = 1; }

message HealthCheckResponse {
  enum ServingStatus {
    UNKNOWN = 0;
    SERVING = 1;
    NOT_SERVING = 2;
  }
  ServingStatus status = 1;
}
```

```rust
impl server::MyService for MyService {
    type CheckFuture =
        future::FutureResult<Response<HealthCheckResponse>, myservice_grpc::tower_grpc::Status>;
    fn check(&mut self, _request: Request<HealthCheckRequest>) -> Self::CheckFuture {
        future::ok(Response::new(HealthCheckResponse {
            status: health_check_response::ServingStatus::Serving as i32,
        }))
    }
}
```

**Comment by seanmonstar** [comment]
It would seem like an unexpected bug, since it looks likek the content-type should be set here: https://github.com/tower-rs/tower-grpc/blob/master/tower-grpc/src/generic/server/streaming.rs#L55

**Comment by brndnmtthws** [comment]
I did some more digging and I've figured out what's going on here. In short:

* tower-grpc doesn't respond with a 404 when there's no matching RPC (this seems like a bug, no?)
* the [grpc health checking protocol doc](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) specifies that:

> A client can query the server’s health status by calling the Check method, and a deadline should be set on the rpc. The client can optionally set the service name it wants to query for health status. The suggested format of service name is package_names.ServiceName, such as grpc.health.v1.Health.

_however_, the `grpc-health-probe` tool doesn't modify the request path when you pass the `-service` flag (which I assumed it did), it merely populates the `service` parameter on the HealthCheckRequest proto with whatever you pass.

One more thing: it's unclear to be if there's a way to use 2 separate protos with the same server. From what I can tell, it's only possible to have one server, so I can't actually use the `grpc-health-probe` tool with tower-grpc unless I fork everything and change the definitions. I wanted to just stick everything in one proto, with one server for simplicity, but I guess that's not practical.

**Comment by seanmonstar** [comment]
Ah, OK. When a gRPC server doesn't recognize a service path, it returns an "unimplemented` response. That still has a 200 OK http status code, because gRPC says so. ;_;

Looks like this is missing setting the header: https://github.com/tower-rs/tower-grpc/blob/master/tower-grpc/src/server/unimplemented.rs

**Comment by LegNeato** [comment]
It looks like UNIMPLEMENTED is supposed to be 501? https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

**Comment by seanmonstar** [comment]
Nope: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses

Notice it shows `:status 200` as constant. And then claims some broken implementations may send non-200 HTTP statuses.

That status code mapping is meant to try to translate when response doesn't conform to gRPC, such as if a proxy is in-between.

**Comment by brndnmtthws** [comment]
For the record, for anyone else wanting to do this, I ended up just making a small binary that implements the same functionality as part of my crate.

Here's the source: https://gist.github.com/brndnmtthws/21a0aa51e21d8b9ae2a1d4dce22cdcbb
