### ISSUE TITLE
Support IDE to recognize the $OUT_DIR generated Rust files

### ISSUE THREAD

**Issue by micfan** [tower-rs/tower-grpc#186]
how to?

eg, in the example

```rust
pub mod hello_world {
    include!(concat!(env!("OUT_DIR"), "/helloworld.rs"));
}
```

the actually included file is
```bash
rpc-server\target\debug\build\tower-grpc-examples-147fe1cec4bcfebf\out\helloworld.rs
```

How to let IntelliJ can jump to this file?

**Comment by mzabaluev** [comment]
> How to let IntelliJ can jump to this file?

Tell them to implement the Language Server Protocol so RLS can do it for them, as it apparently does in Visual Studio Code? :slightly_smiling_face:

**Comment by mzabaluev** [comment]
This issue is not specific to tower-grpc, and is rather a problem of the particular IDE.
