### ISSUE TITLE
Generated code fails clippy

### ISSUE THREAD

**Issue by max-sixty** [tower-rs/tower-grpc#194]
Generated code fails clippy. Unfortunately, clippy's checks seems to lack the configurability to exclude the generated file, restricting dependent projects from running clippy in CI.

Here's an example: https://github.com/andygrove/ballista/pull/31#issuecomment-513368260

Could either fix those issues or add `#![allow(clippy::all)]` to the top of the files

**Comment by seanmonstar** [comment]
You could add that allow on the `mod proto` in the lib.rs file there.

**Comment by max-sixty** [comment]
Great, thanks! Feel free to close this
