### ISSUE TITLE
h2 is dead, long live tower-hyper

### ISSUE THREAD

**Issue by dingxiangfei2009** [tower-rs/tower-grpc#196]
If I understand correctly, `tower-grpc` is using `tower-hyper` exclusively. Shall we remove these conversion functions?

`h2` is dead. Long live `tower-hyper`.

https://github.com/tower-rs/tower-grpc/blob/ea4d6fd95563ae54d0ec900ed01ce0e44b46e404/tower-grpc/src/status.rs#L103

**Comment by seanmonstar** [comment]
Those are internal functions used to translate HTTP2 reset codes into gRPC statuses, and vice versa. The `h2` library implements the HTTP2 protocol, and is still used inside hyper.
