### ISSUE TITLE
impl<T> tower::Service<http::Request<tower_hyper::Body>> is missing in generated code

### ISSUE THREAD

**Issue by abdul-rehman0** [tower-rs/tower-grpc#205]
When I generated route guide proto given in example, it generated all the implementations:

    impl<T> tower::Service<http::Request<grpc::BoxBody>> for RouteGuideServer<T>
    where T: RouteGuide,
    {
      ...
    }

    impl<T> tower::Service<()> for RouteGuideServer<T>
    where T: RouteGuide,
    {
      ...
    }

    impl<T> tower::Service<http::Request<tower_hyper::Body>> for RouteGuideServer<T>
    where T: RouteGuide,
    {
     ...
    }

However, when I generated code for this [cloud_speech](https://github.com/googleapis/googleapis/blob/master/google/cloud/speech/v1p1beta1/cloud_speech.proto) proto using server `true` and client `false`, I got:

    impl<T> tower::Service<http::Request<grpc::BoxBody>> for SpeechServer<T>
    where T: Speech,
    {
      ...
    }

    impl<T> tower::Service<()> for SpeechServer<T>
    where T: Speech,
    {
      ...
    }

`impl<T> tower::Service<http::Request<tower_hyper::Body>>` is missing somehow

Hence, the compilation failed for the following code:

        let handler = Speech {};
        let new_service = server::SpeechServer::new(handler);

        let mut server = Server::new(new_service);

Exact error:

     let mut server = Server::new(new_service);
    |                          ^^^^^^^^^^^ the trait `tower_grpc::codegen::server::tower::Service<hyper::Request<hyper::Body>>` is not implemented for `grpcserversrc::google::cloud::speech::v1p1beta1::server::SpeechServer<grpcserversrc::Speech>`

**Comment by abdul-rehman0** [comment]
`build.rs`

    // Build speech to text proto
    tower_grpc_build::Config::new()
        .enable_client(false)
        .enable_server(true)
        .build(
            &[
                "proto/google/cloud/speech/v1p1beta1/cloud_speech.proto",
                "proto/google/api/annotations.proto",
                "proto/google/api/http.proto",
                "proto/google/longrunning/operations.proto",
                "proto/google/rpc/status.proto",
            ],
            &["proto"],
        )
        .unwrap_or_else(|e| panic!("protobuf compilation failed: {}", e));
    println!("cargo:rerun-if-changed=proto/google/cloud/speech/v1p1beta1/cloud_speech.proto");

**Comment by LucioFranco** [comment]
@abdul-rehman0 just to ensure, do you have the `tower-grpc-build` feature for `tower-hyper` enabled in your cargo.toml?

**Comment by abdul-rehman0** [comment]
@LucioFranco that was it, I enabled `tower-hyper` feature and it worked, Thanks!
