### ISSUE TITLE
Can not use packages with periods/dots in the name. Can't import them?

### ISSUE THREAD

**Issue by rlabrecque** [tower-rs/tower-grpc#211]
Hey everyone, I was trying to use this 'standardized' grpc service proto:

https://github.com/grpc/grpc-proto/blob/master/grpc/health/v1/health.proto

Given `package grpc.health.v1;` tower-grpc outputs `grpc.health.v1.rs` which can not be used like this `pub mod grpc.health.v1;`

The solution based on https://github.com/tower-rs/tower-grpc/issues/129 is to simply rename the package, but that causes the routing in `let path = http::PathAndQuery::from_static("/grpc.health.v1.Health/Check");` to change.

Is there any good solution to this?

**Comment by LucioFranco** [comment]
@rlabrecque I the module becomes one file. You can reference the interop tests which use a nested package name. https://github.com/tower-rs/tower-grpc/blob/master/tower-grpc-interop/src/client.rs#L23

**Comment by rlabrecque** [comment]
Hmm yeah, that test (and the examples) do this which seems kind of clunky?

```
pub mod pb {
    #![allow(dead_code)]
    #![allow(unused_imports)]
    include!(concat!(env!("OUT_DIR"), "/grpc.testing.rs"));
}
```

I suppose that's what I'll end up doing for now, just feels weird compared to

```
pub mod pb {
    pub mod grpc_testing;
}
```

 or ideally:

```
pub mod pb {
   pub mod grpc::testing;
}
``

**Comment by LucioFranco** [comment]
@rlabrecque the later is not possible since you need to import the "raw" code. This is what `include!` does. It pulls in whatever is in that file and places it directly where the macro is.

**Comment by rlabrecque** [comment]
Is there a reason why you have to do that? I was using effectively this until I ran into the dots.
```
pub mod pb {
    pub mod grpc_testing;
}
```

This is definitely a prost problem and not tower-grpc specific though!

https://github.com/danburkert/prost/blob/9551f2852e414df72339634087c46ce5a08e85b2/prost-build/src/lib.rs#L543
