### ISSUE TITLE
Please provide standalone examples

### ISSUE THREAD

**Issue by tomshackell** [tower-rs/tower-grpc#213]
Hi,

It would greatly help to have examples that showed how to consume tower-grpc from another project. The `tower-grpc-examples` seem to only work if compiled from inside the tower source code itself. I'm struggling to work out how to consume `tower-grpc` as an external dependency.

Thanks

Tom

**Comment by LucioFranco** [comment]
@tomshackell hi! You should be able to swap out the path with the released version of `0.1`.

**Comment by tomshackell** [comment]
Hey, so I can replace most of them with the `0.1` version, however the exceptions is  the `[build-dependencies]`. 

So this does work:
```
[build-dependencies]
tower-grpc-build = { git = "https://github.com/tower-rs/tower-grpc", features = ["tower-hyper"] }
```
But this does *not* work:
```
[build-dependencies]
tower-grpc-build = "0.1.0"
```
As the code it generates doesn't compile.

**Comment by davidvartan** [comment]
@tomshackell You still need the `features = ["tower-hyper"]` part there. E.g. I have:

```
tower-grpc-build = { version = "0.1", features = ["tower-hyper"] }
```

**Comment by tomshackell** [comment]
Yup I just worked that out after I typed it (doh!), thanks :)
