### ISSUE TITLE
less description on single example?

### ISSUE THREAD

**Issue by Stvchm9703** [tower-rs/tower-grpc#217]
hi there, I am newer from Rust and this Tower framework ;
so, I download the projects and run the example, 
server-side seem running OK so far,

but I still confuse on a single server-client solution, can it split the example project as three separate rust project ?

thanks

**Comment by LucioFranco** [comment]
Hi! I would suggest using https://github.com/hyperium/tonic instead and you can join our discord server if you have some questions :)
