### ISSUE TITLE
interop test cases for streaming RPCs

### ISSUE THREAD

**Issue by hawkw** [tower-rs/tower-grpc#23]
- [x] `client_streaming`: implemented in client
- [ ] `server_streaming`
- [ ] `ping_pong` (bidi streaming)
- [ ] `empty_stream`

**Comment by hawkw** [comment]
Test cases for compressed streaming have their own issue (#22).

**Comment by per-gron** [comment]
Would it be okay if I tried my hand at these in the coming couple of days? It's labeled as in progress but it seems like it's not actively worked on right now given the date of the last update.

**Comment by hawkw** [comment]
Hi @per-gron, you're right that I haven't been actively working on these tests lately. I have the `server-streaming` test case implemented in [a branch](https://github.com/tower-rs/tower-grpc/tree/eliza/interop-server-streaming), but it's currently blocked by #49. If you'd like to work on the remaining tests (`ping_pong` and `empty_stream`), I haven't started on them yet.

**Comment by hawkw** [comment]
(And if you're interested in looking into issue #49, I've made sure the branch implementing that test is up-to-date)

**Comment by per-gron** [comment]
Done in #71 and #72.
