### ISSUE TITLE
grpc-interop tests run on CI

### ISSUE THREAD

**Issue by hawkw** [tower-rs/tower-grpc#3]
We should put together a set of tests running the [gRPC interoperability test cases](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#interoperability-test-case-descriptions) and run them automatically on CI builds.

**Comment by carllerche** [comment]
Yes!

And generally have tests :)

**Comment by hawkw** [comment]
@carllerche that, too! :)

I was going to assign this issue to myself, but turns out I'm only a collaborator on the `tower-rs/tower` repo.

**Comment by hawkw** [comment]
Apparent hang with the gRPC-interop `large_unary` test, possible flow control issue?

**Comment by carllerche** [comment]
Is it possible to get a subset of the interop tests merged in initially? Just having something running in CI would be a big win.

**Comment by hawkw** [comment]
@carllerche sure, I was thinking about that myself, especially since a number of them depend on TLS and are going to be unimplemented for a while yet. I'll see about getting the current sent to a point where I can open a PR for them.

**Comment by hawkw** [comment]
As of 4d626af12f1ecc908d40bae166f8eca17e12e5b8:

## Current state of test implementation:

We have a test client implementation with a framework for adding more tests. We have not yet implemented a test server, and the `docker-compose` file for running the tests currently runs them against `grpc-go`'s test server for now.

### Test checklist

- [x] `empty_unary`: implemented in client
- [ ] `cacheable_unary`: started, requires request context implementation to set cacheable flag
- [x] `large_unary`: implemented in client, broken due to #14
- [ ] ~`client_compressed_unary`~: requires gRPC compression, NYI
- [ ] ~`server_compressed_unary`~: requires gRPC compression, NYI
- [x] `client_streaming`: implemented in client, broken due to #16
- [ ] ~`client_compressed_streaming`~: requires gRPC compression, NYI
- [ ] `server_streaming`
- [ ] ~`server_compressed_streaming`~: requires gRPC compression, NYI
- [ ] `ping_pong`
- [ ] `empty_stream`
- [ ] ~`compute_engine_creds`~ requires auth, NYI
- [ ] ~`jwt_token_creds`~ requires auth, NYI
- [ ] ~`oauth2_auth_token`~ requires auth, NYI
- [ ] ~`per_rpc_creds`~ requires auth, NYI
- [ ] `custom_metadata`
- [ ] `status_code_and_message`
- [ ] `unimplemented_method`
- [ ] `unimplemented_service`
- [ ] `cancel_after_begin`
- [ ] `cancel_after_first_response`
- [ ] `timeout_on_sleeping_server`
- [ ] ~`concurrent_large_unary`~: not yet added to test case descriptions

**Comment by hawkw** [comment]
Considering closing this issue as a subset of the interop tests _do_ now run on CI, and creating new issue(s) to track the implementation of additional test cases.

**Comment by carllerche** [comment]
That's fine, feel free to do so.

**Comment by hawkw** [comment]
In that case, this was closed by #19.
