### ISSUE TITLE
Handle collisions between message and service names

### ISSUE THREAD

**Issue by hawkw** [tower-rs/tower-grpc#33]
In Conduit, a service called `Destination` has an RPC with a request message type also called `Destination`, imported from another proto file. In the proto file, the request type is namespaced as `common.Destination`.

With the very old version of `tower-grpc` currently vendored by Conduit, `tower-grpc-build` generates code that compiles for this proto, because the RPC request message type is referred to as `super::super::super::common::Destination`. However, in recent git checkouts of `tower-grpc`, `tower-grpc-build` instead generates a `use super::super::super::common::Destination;` statement, and then refers to the type as just `Destination`. This causes a namespace collision with the `Destination` struct that `tower-grpc` defines for that service; the resultant code does not compile.

We should change the way `tower-grpc-build`'s code generation handles cases where messages are defined in other proto files.

**Comment by hawkw** [comment]
I'm considering either:
- detect when an import will cause a namespace collision, and either 
  + namespace the import as `module::Type` rather than `Type`, or
  + rename the import, as `use module::{Type as TypeMsg};`
- or, always namespacing imports as `module::Type`

The second option will probably require less machinery in the `ServiceGenerator` and thus be easier to implement. It also has the advantage of making the generated code look more similar to the input proto.

**Comment by hawkw** [comment]
starting to make some progress on this, but the import scoping mess is somewhat complicated

**Comment by carllerche** [comment]
I would probably opt for option 2, always namespace imports as `module::Type`.

**Comment by hawkw** [comment]
Yeah, that seemed like the best bet to me and is what I've been working on thus far.

**Comment by hawkw** [comment]
Okay, I have this basically working; the current code is a mess, so I'll try to un-bad-ify it a bit before opening a PR.
