### ISSUE TITLE
codegen: case transformations are not applied uniformly

### ISSUE THREAD

**Issue by lucab** [tower-rs/tower-grpc#47]
It looks like there are case transformations applied by prost/t-grpc-build on input protobuf definition, however name mangling doesn't seem to be applied uniformly, resulting in build failures.

A sample case would be the [rkt metadata API](https://github.com/rkt/rkt/blob/v1.29.0/api/v1alpha/api.proto#L460), which contains a service named `PublicAPI` (NB: this follows Go naming convention).

When processing that through prost/t-grpc-build, the generated code has a mix of `API` and `Api`, such as:
```
impl<T> PublicApiServer<T>
where T: PublicApi,
 { ... }

impl<T> tower::Service for PublicApiServer<T>
where T: PublicAPI,
 { ... }

fn call(&mut self, request: Self::Request) -> Self::Future {
  match request.uri().path() {                                
    "/v1alpha.PublicAPI/GetInfo" => { ... }
  ...
}      
```

**Comment by hawkw** [comment]
Hi @lucab, I can reproduce this issue pretty easily with a simple test protobuf. I'll see about fixing it. Thanks for reporting!

**Comment by lucab** [comment]
@hawkw @carllerche thanks for the very quick reaction, confirmed fixed. Now spelunking into grpc-go, I think it doesn't like client with http2 prior-knowledge.

**Comment by carllerche** [comment]
You can perform an ALPN handshake before passing the connection to tower-grpc.

There is an example of how to do the ALPN handshake here: https://github.com/carllerche/h2/blob/master/examples/akamai.rs

**Comment by lucab** [comment]
@carllerche thanks for the hint, but I'm over a unix-domain (or localhost-TCP) socket thus no TLS-ALPN. But I'm just toying around at this point, so it may well be that I'm making a silly mistake somewhere else. I'll report back if I find anything useful at the end of this rabbit hole :)
