### ISSUE TITLE
Option to use different protobuf library

### ISSUE THREAD

**Issue by nevi-me** [tower-rs/tower-grpc#76]
I've tried using tower as it has better support for streaming relative to the other grpc libraries that I've tried.

I've so far found prost to be difficult to use, as it seems not to have a way to initialise empty proto messages.

I have "large" messages with up to 14 fields, and having to create

```rust
let mut message = myproto::Message {
  field1 = vec![],
  field2 = String::from_str("")
  // ...
  field14 = 0.0f64
}
```

is a lot more laborious than `let mut message = myproto::Message::new()`.

___

How pluggable is the underlying protobuf implementation? I've opened https://github.com/danburkert/prost/issues/121 on prost to find out if I'm maybe not using it correctly.

**Comment by carllerche** [comment]
Switching to a different protobuf lib is low priority for us right now. Given @per-gron's inisght on the referenced ticket, I'm going to close this.
