### ISSUE TITLE
Status doesn't take a message String

### ISSUE THREAD

**Issue by illicitonion** [tower-rs/tower-grpc#77]
It looks like `tower_grpc::Status` currently only encapsulates the status code enum, and not the optional String description. Is this an intentional decision, or a haven't-gotten-around-to-it? Either way, is this a big scary thing, or simple a matter of adding a field and serializing the bytes in the right place?

The existence of https://github.com/tower-rs/tower-grpc/issues/28 suggests that this is intended to be addressed at some point. Any pointers/warnings before I jump in and add it? :)

Thanks!

**Comment by gwihlidal** [comment]
I would absolutely love to get the status message, as well. +1! I'm hitting this exact issue right now.

**Comment by seanmonstar** [comment]
This was definitely a we-didn't-need-it-yet-so-we-didn't-dedicate-thought-to-it. We should add it, for sure. Would you like to outline what changes could be made to the API to expose this?
