### ISSUE TITLE
Metadata support

### ISSUE THREAD

**Issue by D4nte** [tower-rs/tower-grpc#79]
Hi,

If I understand correctly, metadata support (e.g. for authentication using macaroons) is not yet supported?

Is there an issue to track the implementation support so I can keep an eye on it?

Thanks!

**Comment by D4nte** [comment]
So apparently custom-metadata is an [HTTP2 thing](https://godoc.org/google.golang.org/grpc/metadata) I wonder if it's possible to set the metadata in the tower when setting up the HTTP connection.

**Comment by seanmonstar** [comment]
Yea, metadata is sent via headers. The underlying service could be used to add or read metadata, in that they can do anything with headers. It's probably also a good idea to have metadata helper methods in this crate, since there's some rules around binary encoded metadata headers for grpc.

**Comment by D4nte** [comment]
Ok I was able to set the header manually.

See #80.

I am guessing the rule you are mentioning @seanmonstar is that binary header should be encoded in base64?

I could add a binary example to #80 if you think it's worth it.

**Comment by seanmonstar** [comment]
There is now extensive metadata support for requests and responses.
