### ISSUE TITLE
Spurious import of `()`

### ISSUE THREAD

**Issue by kinnison** [tower-rs/tower-grpc#81]
Hi,

When using a proto which defines a service taking or returning `google.protobuf.Empty`, by default prost will convert that to `()` which it then supports directly.  Sadly this means that the generated service code from `tower-grpc-build` ends up with an attempt to import `super::()` in a number of places.

I could litter the `server.rs` and `client.rs` with loads of `if foobartype != "()" {` around the calls to `.import_type()` and `.import()` but this feels clunky.  It'd be nice if there were a cleaner fix, but if there is, I can't see it.  My dodgy hack will let me proceed, and I can reflow it and supply it in a PR if desired, but essentially `input_type` and `output_type` from the `prost_build::Module` need to be checked wherever they might be imported, so that we don't generate an import of `()`.

An example proto which uses this is `google.longrunning.operations` in the `Operations` service there's `DeleteOperation` which returns `google.protobuf.Empty` as does `CancelOperation` at the same level.  (Proto example is [here](https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto))

**Comment by kinnison** [comment]
Also, since it doesn't seem sane to hide it from you, you can find my shonky commit on my fork at https://github.com/kinnison/tower-grpc

**Comment by kinnison** [comment]
Oh and again, I should note that this is only important if you're using prost master (since August 1st when the type mapping was amended using their `extern_path` logic)

**Comment by hawkw** [comment]
Hi @kinnison, if you're interested, I think a PR would be welcome!

**Comment by kinnison** [comment]
I think that makes a lot of sense yes.  I will see if I can get some time to look at it, but if someone else looks at what I did and writes a better patch I won't feel bad :-)

**Comment by seanmonstar** [comment]
I *believe* this should be done thanks to https://github.com/tower-rs/tower-grpc/pull/140/files#diff-d15ac6177e75577c93c4041346f98ed0R182
