### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shinzui** [tower-rs/tower-grpc#87]
Is there a roadmap of what's required before this library becomes production ready? Is anyone already using it in production? We prototyped a low-risk service with tower-grpc that we're about to deploy to production, but we don't feel comfortable writing core services in rust until there is a production-ready gRPC library.

**Comment by carllerche** [comment]
People are using it in production, but the library is young and under active development.

I hope to get this to crates.io soon(ish) but there will be significant API changes before then. Hopefully that will happen by the end of 2018.

**Comment by shinzui** [comment]
@carllerche it's great to hear that it's being used in production and that it's under active development. That will make adopting Rust for some services easier. 
Thank you.
