### ISSUE TITLE
Retain inline Protobuf comments in generated code

### ISSUE THREAD

**Issue by ebkalderon** [tower-rs/tower-grpc#96]
One nice feature of Prost is its ability to retain the inline comments on Protobuf types and their fields as doc comments in the generated Rust code. However, it seems that the builder from `tower-grpc-build` doesn't retain them for the client/server traits, structs, and methods. It would be nice to include those comments in the generated code as well.

**Comment by hawkw** [comment]
Fixed by #112!

**Comment by ebkalderon** [comment]
@hawkw Fantastic!
